site_name: ECNet Documentation
nav:
  - Installation: index.md
  - API Documentation:
    - ecnet.model: api_model.md
    - ecnet.datasets: api_datasets.md
    - ecnet.tasks: api_tasks.md
    - ecnet.blends: api_blends.md
    - ecnet.callbacks: api_callbacks.md
theme: material
plugins:
  - search
  - mkdocstrings
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
